---
- import_tasks: add-key.yml

- name: Add PHP repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/php-sury-repo.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main

- name: Install xdebug control scripts
  template:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - src: "{{ php_xdebug_control_script_enable }}"
    dest: xdebug-enable
  - src: "{{ php_xdebug_control_script_disable }}"
    dest: xdebug-disable
  when: php_fpm_xdebug or php_cli_xdebug
