---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update APT
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install system packages
  apt:
    pkg: "{{ base_default_system_packages + system_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Generate required locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{system_locales}}"

- name: Set default locale
  copy:
    content: "LANG=\"{{ system_default_locale }}\"\n"
    dest: /etc/default/locale

- name: Set default timezone
  timezone:
    name: "{{ system_timezone }}"
  notify: restart cron

- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    append: yes
    groups: "{{ item.groups|default(omit) }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Assign authorized keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ lookup('file', item.1) }}"
  with_subelements:
    - "{{ users }}"
    - authorized_keys
  loop_control:
    label: "{{ item.0.name }} - {{ item.1 }}"
