---
- name: "Set vars for user {{ gpg_user_config.user }}"
  set_fact:
    gpg_basedir: "{{ gpg_user_config.gpg_basedir|default(gpg_default_basedir) }}"

- name: "Ensure {{ gpg_basedir }} directory exists with secure permissions"
  file:
    dest: "{{ gpg_basedir }}"
    state: directory
    mode: 0700

- name: Import private keys
  include_tasks: private_keys.yml
  with_items: "{{ gpg_user_config.private_keys }}"
  loop_control:
    loop_var: gpg_user_private_key

- name: Import public keys
  include_tasks: public_keys.yml
  with_items: "{{ gpg_user_config.public_keys }}"
  loop_control:
    loop_var: gpg_user_public_key
