---
- name: Install SSL private keys
  copy:
    content: "{{ item.data|b64decode }}"
    dest: "/etc/ssl/private/{{ item.name }}.key"
    owner: root
    group: ssl-cert
    mode: 0640
  with_items: "{{ ssl_keys }}"
  no_log: true

- name: Install SSL certificates
  copy:
    content: "{{ item.data|b64decode }}"
    dest: "/etc/ssl/certs/{{ item.name }}.pem"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ ssl_certs }}"

- name: Install SSL stapling certificates
  copy:
    content: "{{ item.data|b64decode }}"
    dest: "/etc/ssl/certs/{{ item.name }}.stapling.pem"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ ssl_stapling }}"

- name: Create DH folder
  file:
    path: /etc/ssl/dh
    state: directory
    owner: root
    group: ssl-cert
    mode: 0710

- name: Generate DH params
  command: openssl dhparam -out /etc/ssl/dh/dhparam.pem 2048
  args:
    creates: /etc/ssl/dh/dhparam.pem

- name: Secure DH params # secure to do this after creation due to folder perms
  file:
    path: /etc/ssl/dh/dhparam.pem
    state: file
    owner: root
    group: ssl-cert
    mode: 0640
