---
- name: Add Google repo key
  apt_key:
    data: "{{ lookup('file', 'google-repo.asc') }}"
    state: present

- name: Add chrome repo # this file is clobbered by chrome so can't use https
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome

- name: Install chrome
  apt:
    pkg: google-chrome-stable
    state: present
    update_cache: yes
    cache_valid_time: 3600

- import_tasks: chromedriver.yml
  when: chrome_install_chromedriver
