---
- name: Remove system chrome
  include_tasks: remove-system-chrome.yml
  when: chrome_remove_system_chrome

- name: Install chrome
  command: npx --yes @puppeteer/browsers install chrome@stable --path /opt
  register: chrome_install_result

- name: Process chrome path
  set_fact:
    chrome_path: "{{ chrome_install_result.stdout|regex_search('chrome@[\\d.]+ (.+)', '\\1')|first }}"

- name: Link chrome
  file:
    src: "{{ chrome_path }}"
    dest: /usr/local/bin/google-chrome
    state: link
    force: true

- import_tasks: chromedriver.yml
  when: chrome_install_chromedriver
