---
- name: Add Google repo key
  apt_key:
    data: "{{ lookup('file', 'google-repo.asc') }}"
    state: present

- name: Add chrome repo # this file is clobbered by chrome so can't use https
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome

- name: Install chrome
  apt:
    pkg: google-chrome-stable,libgconf-2-4
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Check existing chromedriver version
  command: /usr/local/bin/chromedriver --version
  changed_when: chrome_chromedriver_version_result is failed or chrome_chromedriver_version|string not in chrome_chromedriver_version_result.stdout
  failed_when: chrome_chromedriver_version_result.rc not in [0, 2]
  register: chrome_chromedriver_version_result

- block:
  - name: Get temporary path for chromedriver download
    tempfile:
      state: file
      suffix: .chromedriver.zip
    register: chrome_chromedriver_download_path

  - name: Download chromedriver
    get_url:
      url: "{{ chrome_chromedriver_download_url }}"
      dest: "{{ chrome_chromedriver_download_path.path }}"
      owner: root
      group: root
      mode: 0600
      checksum: "{{ chrome_chromedriver_checksum }}"

  - name: Unpack chromedriver
    unarchive:
      src: "{{ chrome_chromedriver_download_path.path }}"
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755
  when: chrome_chromedriver_version_result is changed
