---
- name: Per-user AWS install and config
  become: yes
  become_user: "{{ aws_cli_user_config.user }}"
  include_tasks: install.yml
  with_items: "{{ aws_cli_config }}"
  loop_control:
    loop_var: aws_cli_user_config
