---
postgres_databases: []
postgres_users: []
postgres_privs: []
postgres_extensions: []

postgres_default_packages:
- "postgresql-{{ postgres_version }}"
- "postgresql-client-{{ postgres_version }}"
- python3-psycopg2
postgres_additional_packages: []

# Memory assumed at 2GB
postgres_shared_buffers: 512MB # 1/4 ram
postgres_effective_cache_size: 1GB # 1/2 ram
postgres_max_connections: 100

# The following option can cause unrecoverable data corruption on a system crash but results in a large speed increase.
# Only set to false if data is disposable.
postgres_risky_fast: false
postgres_full_page_writes: "{{ 'off' if postgres_risky_fast else 'on' }}"
postgres_synchronous_commit: "{{ 'off' if postgres_risky_fast else 'on' }}"
postgres_fsync: "{{ 'off' if postgres_risky_fast else 'on' }}"

postgres_max_wal_size: 1GB

postgres_locale: "{{ system_default_locale|default('en_GB.UTF-8') }}"
