---
- name: Install PHP CLI
  apt:
    pkg: "php{{ php_cli_version }}-cli"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install PHP packages
  apt:
    pkg: "{{ php_cli_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install Xdebug
  apt:
    pkg: php{{ php_cli_version }}-xdebug
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: php_cli_xdebug
  register: php_cli_xdebug_installed

- name: Disable xdebug by default
  file:
    path: "/etc/php/{{ php_cli_version }}/cli/conf.d/20-xdebug.ini"
    state: absent

- name: Apply PHP CLI settings
  template:
    src: "{{ lookup('first_found', [role_path~'/templates/php'~php_cli_version~'.ini.j2', role_path~'/templates/php.ini.j2']) }}"
    dest: "/etc/php/{{ php_cli_version }}/cli/php.ini"
    owner: root
    group: root
    mode: 0644

# TODO: review security
#- name: Ensure opcache file cache dir exists
#  file:
#    path: "{{ php_cli_opcache_file_cache }}"
#    owner: root
#    group: root
#    mode: 0777
#    state: directory
#  when: php_cli_opcache_file_cache_only == 1
