---
# This is to be applied to the machine that creates the database dump and uploads it to the server
- name: "Add private key to {{ dbcd_client_user }} user"
  copy:
    content: "{{ dbcd_client_private_key }}"
    dest: "/home/{{ dbcd_client_user }}/.ssh/dbcd"
    owner: "{{ dbcd_client_user }}"
    group: "{{ dbcd_client_user }}"
    mode: 0600

- name: "Add dbcd server ssh config"
  blockinfile:
    block: |
      Host dbcd-server-w
        HostName {{ dbcd_server_host }}
        User {{ dbcd_server_user }}
        IdentityFile ~/.ssh/dbcd
        IdentitiesOnly yes
    path: "/home/{{ dbcd_client_user }}/.ssh/config"
    owner: "{{ dbcd_client_user }}"
    group: "{{ dbcd_client_user }}"
    create: true
    mode: 0600
    marker: "# {mark}-DBCD-W ANSIBLE MANAGED BLOCK"

- name: "Add dbcd server to known hosts"
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    line: "{{ item }}"
    create: yes
    owner: root
    group: root
    mode: 0644
  with_items: "{{ dbcd_known_hosts }}"
