---
- name: Install Node repo key
  apt_key:
    data: "{{ lookup('file', 'nodesource-repo.asc') }}"
    state: present

- import_tasks: remove-old-node-repo.yml

- name: Add Node repo
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://deb.nodesource.com/node_{{ node_apt_version }} nodistro main"
    - "deb-src https://deb.nodesource.com/node_{{ node_apt_version }} nodistro main"
  register: node_repo

- name: Install Node
  apt:
    pkg: nodejs
    state: "{{ node_repo.changed | ternary('latest', 'present') }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Write .npmrc
  template:
    src: "node/{{ item.template }}"
    dest: "{{ item.dir }}/.npmrc"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0600
  with_items: "{{ node_npmrc }}"

- name: Install Node global packages
  npm:
    name: "{{ item }}"
    global: yes
    production: yes
  with_items: "{{ node_global_packages }}"
