---
- name: Install Node repo key
  copy:
    src: nodesource.gpg
    dest: /usr/share/keyrings/nodesource.gpg
    owner: root
    group: root
    mode: 0644

- import_tasks: remove-old-node-repo.yml

- name: Add Node repo
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x nodistro main"
    - "deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x nodistro` main"
  register: node_repo

- name: Install Node
  apt:
    pkg: nodejs
    state: "{{ node_repo.changed | ternary('latest', 'present') }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Write .npmrc
  template:
    src: "node/{{ item.template }}"
    dest: "{{ item.dir }}/.npmrc"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0600
  with_items: "{{ node_npmrc }}"

- name: Install Node global packages
  npm:
    name: "{{ item }}"
    global: yes
    production: yes
  with_items: "{{ node_global_packages }}"
