---
- name: "Remove Node {{ node_version }} old repo"
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
