---
- name: "Remove Node {{ version }} repo"
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb https://deb.nodesource.com/node_{{ version }} nodistro main"
    - "deb-src https://deb.nodesource.com/node_{{ version }} nodistro main"
