---
- name: "Remove Node {{ node_apt_version }} old repo"
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_apt_version }} {{ ansible_distribution_release }} main"
    - "deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_apt_version }} {{ ansible_distribution_release }} main"
