---
php_cli_version: "{{ php_version }}"
php_cli_date_timezone: Europe/London
php_cli_error_reporting: E_ALL & ~E_DEPRECATED & ~E_STRICT
php_cli_display_errors: Off
php_cli_display_startup_errors: Off
php_cli_error_log: syslog
php_cli_mysqlnd_collect_statistics: Off
php_cli_xdebug: false
php_cli_xdebug_remote_enable: true
php_cli_xdebug_remote_host: "{{ php_cli_xdebug_client_host }}"
php_cli_xdebug_remote_autostart: true
php_cli_xdebug_client_host: "{{ php_xdebug_client_host|default('') }}"
php_cli_xdebug_idekey: cli
php_cli_xdebug_max_nesting_level: 500
php_cli_packages: "{{ php_packages|default([]) }}"
