---
- name: Install GPG
  apt:
    pkg: gpg
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Add DO Agent repo key
  apt_key:
    data: "{{ lookup('file', lookup('first_found', ['do-agent-repo.asc', 'roles/do-agent/files/do-agent-repo.asc'])) }}"
    state: present
