---
- name: Add repo key
  copy:
    src: digitalocean-agent-keyring.gpg
    dest: /usr/share/keyrings/digitalocean-agent-keyring.gpg
    owner: root
    group: root
    mode: 0644

- name: Add repository
  apt_repository:
    filename: digitalocean-agent
    repo: deb [signed-by=/usr/share/keyrings/digitalocean-agent-keyring.gpg] https://repos.insights.digitalocean.com/apt/do-agent main main

- name: Install agent
  apt:
    pkg: do-agent
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure agent is started and enabled
  systemd:
    name: do-agent
    enabled: true
    state: started
