---
- name: "Remove Node {{ version }} repo"
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ version }}.x nodistro main"
    - "deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ version }}.x nodistro main"
