---
- name: Install Shorewall
  apt:
    pkg: shorewall,shorewall6,fail2ban,python-pyinotify
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify:
  - restart shorewall
  - restart shorewall6
  - restart fail2ban

- name: Configure ipv4
  template:
    src: "shorewall/{{ item.src }}"
    dest: "/etc/shorewall/{{ item.dest }}"
  with_items:
  - { src: interfaces.j2, dest: interfaces }
  - { src: policy.j2, dest: policy }
  - { src: rules.j2, dest: rules }
  - { src: shorewall.conf.j2, dest: shorewall.conf }
  - { src: zones.j2, dest: zones }
  register: reg_shorewall_configure

- name: Test ipv4
  command: shorewall check
  when: reg_shorewall_configure is changed
  notify: restart shorewall

- name: Configure ipv6
  template:
    src: "shorewall6/{{ item.src }}"
    dest: "/etc/shorewall6/{{ item.dest }}"
  with_items:
  - { src: interfaces.j2, dest: interfaces }
  - { src: policy.j2, dest: policy }
  - { src: rules.j2, dest: rules }
  - { src: shorewall6.conf.j2, dest: shorewall6.conf }
  - { src: zones.j2, dest: zones }
  register: reg_shorewall6_configure

- name: Test ipv6
  command: shorewall6 check
  when: reg_shorewall6_configure is changed
  notify: restart shorewall6

- name: Configure defaults
  template:
    src: "default/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: shorewall.j2, dest: /etc/default/shorewall }
  - { src: shorewall6.j2, dest: /etc/default/shorewall6 }

- name: Enable ipv4 service
  service:
    name: shorewall
    enabled: "{{ shorewall_enable }}"

- name: Enable ipv6 service
  service:
    name: shorewall6
    enabled: "{{ shorewall_enable }}"

- name: Configure fail2ban
  template:
    src: fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban
