---
- import_tasks: add-key.yml

- name: Add PHP repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/php-sury-repo.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main

- name: Install xdebug control scripts
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - xdebug-enable
  - xdebug-disable
  when: php_fpm_xdebug or php_cli_xdebug
