---
- name: Check if certificate already exists
  stat:
    path: '/etc/letsencrypt/live/{{ certbot_certs_item.domains | first }}/cert.pem'
  register: certbot_certs_item_stat

- name: Create certificate
  command: "certbot certonly --{{ certbot_mode }} --noninteractive --agree-tos --email {{ certbot_certs_item.admin_email }} -d {{ certbot_certs_item.domains | join(',') }} {{ certbot_dry_run | ternary('--dry-run', '') }}"
  when: not certbot_certs_item_stat.stat.exists

- name: Patch standalone authentication to Nginx
  lineinfile:
    path: '/etc/letsencrypt/renewal/{{ certbot_certs_item.domains | first }}.conf'
    search_string: '{{ item.search }}'
    line: '{{ item.replace }}'
    insertafter: '\[renewalparams\]'
  with_items:
  - {search: 'authenticator = standalone', replace: 'authenticator = nginx'}
  - {search: 'installer = None', replace: 'installer = nginx'}
