---
- name: Install DO DNS plugin
  ansible.builtin.apt:
    name: python3-certbot-dns-digitalocean
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Create DO DNS credentials file
  ansible.builtin.copy:
    content: |
      dns_digitalocean_token = "{{ certbot_digitalocean_dns_token }}"
    dest: /etc/letsencrypt/digitalocean.ini
    owner: root
    group: root
    mode: '0600'

- with_items: '{{ certbot_certs }}'
  ansible.builtin.include_tasks: dns-digitalocean-certs.yml
  loop_control:
    loop_var: certbot_certs_item
    label: "{{ certbot_certs_item.name }}"
  when: certbot_certs|length
