---
- name: "Create certificate {{ certbot_certs_item.name }}"
  ansible.builtin.command: >
    certbot certonly
    --dns-digitalocean
    --dns-digitalocean-credentials /etc/letsencrypt/digitalocean.ini
    --non-interactive
    --agree-tos
    --email "{{ certbot_certs_item.admin_email }}"
    --domains "{{ certbot_certs_item.domains | join(',') }}"
    --cert-name "{{ certbot_certs_item.name }}"
    {{ certbot_dry_run | ternary('--dry-run', '') }}
  args:
    creates: "/etc/letsencrypt/live/{{ certbot_certs_item.name }}/cert.pem"
