---
- name: Install Redis
  apt:
    pkg: redis-server
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Add vm.overcommit_memory = 1 to sysctl
  sysctl:
    name: vm.overcommit_memory
    value: 1
    reload: yes
