---
- name: Install git
  apt:
    pkg: git
    default_release: "{{ ansible_distribution_release }}-backports"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Add repository SSH known hosts # prevents issue with interactive question on unknown host
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    line: "{{ item }}"
    create: yes
    owner: root
    group: root
    mode: 0644
  with_items: "{{git_known_hosts}}"

- name: Rewrite deprecated git protocol
  blockinfile:
    path: /etc/gitconfig
    block: |
      [url "https://"]
        insteadOf = git://
    create: yes
    owner: root
    group: root
    mode: '0644'
  when: git_rewrite_deprecated_protocol