---
- name: restart cron
  service:
    name: cron
    state: restarted
    enabled: yes

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: update timezone
  command: dpkg-reconfigure -f noninteractive tzdata
