---
- name: Install rsync
  apt:
    pkg: rsync
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Link rrsync
  file:
    src: /usr/share/doc/rsync/scripts/rrsync
    dest: /usr/local/bin/rrsync
    state: link
    owner: root
    group: root
    mode: 0755
